//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        public Nullable<int> StateId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Communication_Type { get; set; }
        public string Description { get; set; }
        public string F6 { get; set; }
        public int CommunicationId { get; set; }
    
        public virtual State State { get; set; }
    }
}
