//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemographicDataReport
    {
        public Nullable<int> StateId { get; set; }
        public Nullable<double> Days_Since_Last_Update { get; set; }
        public Nullable<System.DateTime> Date_Last_File_Sent { get; set; }
        public string Status { get; set; }
        public int DemographicDataReportId { get; set; }
    
        public virtual State State { get; set; }
    }
}
