//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StateTrackerContext : DbContext
    {
        private class StateTrackerContextInitializer : CreateDatabaseIfNotExists<StateTrackerContext>
        {
        }

        public StateTrackerContext()
            : base("name=StateTrackerContext")
        {
            Database.SetInitializer<StateTrackerContext>(new StateTrackerContextInitializer());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssessmentReport> AssessmentReports { get; set; }
        public virtual DbSet<Communication> Communications { get; set; }
        public virtual DbSet<DemographicDataReport> DemographicDataReports { get; set; }
        public virtual DbSet<LastUpdateReport> LastUpdateReports { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<StateCharacteristic> StateCharacteristics { get; set; }
        public virtual DbSet<StateLeadContact> StateLeadContacts { get; set; }
        public virtual DbSet<StateLocation> StateLocations { get; set; }
        public virtual DbSet<StateTechnicalContact> StateTechnicalContacts { get; set; }
        public virtual DbSet<StateVendor> StateVendors { get; set; }
        public virtual DbSet<StateVendorContact> StateVendorContacts { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VendorContact> VendorContacts { get; set; }
    }
}
