//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateCharacteristic
    {
        public Nullable<int> StateId { get; set; }
        public Nullable<double> TBD1 { get; set; }
        public Nullable<double> TBD2 { get; set; }
        public int CharacteristicId { get; set; }
        public Nullable<long> Population { get; set; }
    
        public virtual State State { get; set; }
    }
}
