//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorContact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorContact()
        {
            this.StateVendorContacts = new HashSet<StateVendorContact>();
        }
    
        public int VendorContactId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
        public string Phone_ { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateVendorContact> StateVendorContacts { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
